version: "3"
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data_single:/bitnami/zookeeper
    networks:
      - bobafett-net

  kafka1:
    image: 'bitnami/kafka:3'
    container_name: kafka1
    hostname: kafka1
    ports:
      - 19092   # just within docker network
      - '9092:9092'   # localhost mapping
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_PORT=9999  # for JMX metrics
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:19092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - kafka1_data_single:/bitnami/kafka
      - ./scripts/kafka-server-start.sh:/opt/bitnami/kafka/bin/kafka-server-start.sh  # custom-startup-script with JMX_PORT enabled
    networks:
      - bobafett-net


  kafka-manager:
    image: 'elephantscale/kafka-manager'
    container_name: kafka-manager
    hostname: kafka-manager
    depends_on:
      - zookeeper
    ports:
      - '9000:9000'   # localhost mapping
    restart: unless-stopped
    environment:
      - ZK_HOSTS=zookeeper:2181
    networks:
      - bobafett-net

      

volumes:
  zookeeper_data_single:
    driver: local
  kafka1_data_single:
    driver: local

networks:
  bobafett-net:
    driver: bridge
    name: bobafett-net
