version: "3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
     - 2181:2181
    volumes:
      - zookeeper_data_single:/var/lib/zookeeper:z

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 19092   # just within docker network
      - '9092:9092'   # localhost mapping
      # -  9991:9991  # JMX
    # container_name: kafka1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_PORT=9999  # for JMX metrics
      # - KAFKA_HEAP_OPTS='-Xmx512M -Xms512M'
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - LISTENERS=CLIENT://:19092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka1:19092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - CONFLUENT_METRICS_ENABLE='false'
      # - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=kafka1:19092
      # - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka1_data_single:/var/lib/kafka:z


  kafka-cluster-manager:
    build:
      context: kafka-cluster-manager
    depends_on:
      - zookeeper
    ports:
      - '9000:9000'   # localhost mapping
    restart: unless-stopped
    environment:
      - ZK_HOSTS=zookeeper:2181

      
  python-dev:
    image: kafka-python-dev  # this is built locally
    build:
      context: python-dev
    command: ["/bin/bash"]
    working_dir: '/work'
    user: ${CURRENT_USER}
    volumes:
      - ./work:/work:z   # for sharing files from host


volumes:
  zookeeper_data_single:
    driver: local
  kafka1_data_single:
    driver: local