{
 "title": "kafka metrics1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "*.kafka-metrics1.producer.events.m1_rate"
    }
   ]
  },
  {
   "title": "Producer events count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "*.kafka-metrics1.producer.events.count"
    }
   ]
  },
  {
   "title": "Consumer events count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "*.kafka-metrics1.consumer.events.count"
    }
   ]
  },
  {
   "title": "Consumer events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "*.kafka-metrics1.consumer.events.m1_rate"
    }
   ]
  },
  {
   "title": "Consumer processing time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "*.kafka-metrics1.consumer.processing-time.m1_rate"
    }
   ]
  }
 ]
}