{
 "title": "metrics-demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "demo.counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "metrics-demo.demo.counter.count"
    }
   ]
  },
  {
   "title": "demo.histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "target": "metrics-demo.demo.histogram.mean"
    }
   ]
  },
  {
   "title": "demo.meter (timeseries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "metrics-demo.demo.meter.m1_rate"
    },
    {
     "target": "metrics-demo.demo.meter.m5_rate"
    }
   ]
  },
  {
   "title": "demo.meter (gauge style)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "metrics-demo.demo.meter.m1_rate"
    }
   ]
  },
  {
   "title": "demo.gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "metrics-demo.demo.gauge" }
   ]
  },
  {
   "title": "demo.timer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    { "target": "metrics-demo.demo.timer.mean" }
   ]
  }
 ]
}